n1 = int(input("Enter the 1st number : "))
n2 = int(input("Enter the 2nd number : "))
n3 = int(input("Enter the 3rd number : "))
n4 = int(input("Enter the 4th number : "))
n5 = int(input("Enter the 5th number : "))
n6 = int(input("Enter the 6th number : "))
n7 = int(input("Enter the 7th number : "))
n8 = int(input("Enter the 8th number : "))

s = set()
s.add(n1)
s.add(n2)
s.add(n3)
s.add(n4)
s.add(n5)
s.add(n6)
s.add(n7)
s.add(n8)

print("Displaying all unique numbers : " , s)